### ISSUE TITLE
example sitk readers expect str args in py2

### ISSUE THREAD

**Issue by mrajchl** [DLTK/DLTK#17]
got error `Wrong number or type of arguments for overloaded function 'ReadImage'.
  Possible C/C++ prototypes are:
    itk::simple::ReadImage(std::vector< std::string,std::allocator< std::string > > const &,itk::simple::PixelIDValueEnum)
    itk::simple::ReadImage(std::string const &,itk::simple::PixelIDValueEnum)
 from `_read_sample`:
Traceback (most recent call last):
  File "/vol/medic01/users/mrajchl/repos/DLTK/src/dltk/io/abstract_reader.py", line 115, in f
    ex = next(fn)
  File "/vol/medic01/users/mrajchl/repos/DLTK/src/examples/applications/MRBrainS13_tissue_segmentation/reader.py", line 47, in read_fn
    t1_sitk = sitk.ReadImage(os.path.join(str(img_fn), 'T1.nii'))

**Comment by mrajchl** [comment]
Only relevant for MRBrainS example. Fixed with f95bc75
