### ISSUE TITLE
RuntimeError: generator raised StopIteration - IXI_HH_sex_classification_resnet

### ISSUE THREAD

**Issue by FilipaMarques** [DLTK/DLTK#42]
I'm trying to run **IXI_HH_sex_classification_resnet**. I have managed to adapt the reader.py to my particular case but when I tried running **train.py, the following error arose**:

`2019-06-07 16:08:54.017597: W tensorflow/core/framework/op_kernel.cc:1389] Unknown: RuntimeError: generator raised StopIteration
Traceback (most recent call last):

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\dltk\io\abstract_reader.py", line 115, in f
    ex = next(fn)

StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\ops\script_ops.py", line 207, in __call__
    ret = func(*args)

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 449, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

RuntimeError: generator raised StopIteration

Traceback (most recent call last):
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: RuntimeError: generator raised StopIteration
Traceback (most recent call last):

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\dltk\io\abstract_reader.py", line 115, in f
    ex = next(fn)

StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\ops\script_ops.py", line 207, in __call__
    ret = func(*args)

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 449, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

RuntimeError: generator raised StopIteration

	 [[{{node PyFunc}}]]
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Utilizador/PycharmProjects/TesePrimeiraTentativa/main.py", line 203, in <module>
    steps=EVAL_EVERY_N_STEPS)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1158, in _train_model_default
    saving_listeners)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1407, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\training\monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: RuntimeError: generator raised StopIteration
Traceback (most recent call last):

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\dltk\io\abstract_reader.py", line 115, in f
    ex = next(fn)

StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\ops\script_ops.py", line 207, in __call__
    ret = func(*args)

  File "C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 449, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

RuntimeError: generator raised StopIteration

	 [[{{node PyFunc}}]]
	 [[node IteratorGetNext (defined at C:\Users\Utilizador\Anaconda3\envs\TensorFlow-GPU-Kera\lib\site-packages\dltk\io\abstract_reader.py:140) ]]

Process finished with exit code 1
`

I believe it can be one of two things:
1) A **version incompatibility error**: python 3.7.3; dltk 0.2.1; tensorboard 1.13.1; tensorflow-estimator 1.13.0; tensorflow-gpu 1.13.1)
2) A **memory error**: when "Reading" the last image, the following text is outputed

`2019-06-07 16:08:21.286693: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 585.09MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-06-07 16:08:21.319659: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-06-07 16:08:21.490547: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-06-07 16:08:21.649967: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 585.09MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
`

**Comment by mrajchl** [comment]
Hi, 
two things I see here: 1. your generator is returning a stop iteration, causing the error. this could mean your reader/generator ran out of examples to provide to the training. 2. the tensorflow warnings state, that you are allocating too much memory on your GPU. I would solve this first. This is however not a DLTK issue and i am closing this. 

If you need help with your code, write to our gitter chat https://gitter.im/DLTK/DLTK . 

HTH,
M

**Comment by anindox8** [comment]
Hi guys.

For future reference:

I was running into the same error. In my case, it was because of Python 3.7, which might be the case for you or any others running into this thread in the future. The following excerpt perfectly captures what's happening and helped me solve my issue:

https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app/51701040#51701040?newreg=0c55af46a94947e4bcb18737835843e7

In your case, you would have to switch 

```
except (tf.errors.OutOfRangeError, StopIteration):
    raise
```
to 

```
except (tf.errors.OutOfRangeError, StopIteration):
    return
```

in 'dltk\io\abstract_reader.py'.

Hope this helps!

**Comment by hosein9112400382** [comment]
> Hi guys.
> 
> For future reference:
> 
> I was running into the same error. In my case, it was because of Python 3.7, which might be the case for you or any others running into this thread in the future. The following excerpt perfectly captures what's happening and helped me solve my issue:
> 
> https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app/51701040#51701040?newreg=0c55af46a94947e4bcb18737835843e7
> 
> In your case, you would have to switch
> 
> ```
> except (tf.errors.OutOfRangeError, StopIteration):
>     raise
> ```
> 
> to
> 
> ```
> except (tf.errors.OutOfRangeError, StopIteration):
>     return
> ```
> 
> in 'dltk\io\abstract_reader.py'.
> 
> Hope this helps!
Thank you... you saved my time.

**Comment by hosein9112400382** [comment]
very thanks anindox8.
you saved my time.
