### ISSUE TITLE
ERROR extracting IXI HH Data from t1.tar

### ISSUE THREAD

**Issue by regmibijay** [DLTK/DLTK#45]
> System : Ubuntu Server 18.04
> Python : 2.7 
> All of prerequisites installed.

While running `/data/download_IXI_HH.py`, the script throws 

```
Extracting IXI HH data from t2.tar.
Extracting IXI HH data from mra.tar.
Extracting IXI HH data from pd.tar.
Extracting IXI HH data from t1.tar.
[u'Table', u'Ethnicity', u'Marital Status', u'Occupation', u'Qualification', u'Study Date']
download_IXI_HH.py:139: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  na_values=[]).as_matrix()
Resampling IXI012
Traceback (most recent call last):
  File "download_IXI_HH.py", line 150, in <module>
    t1 = sitk.ReadImage(t1_fn)
  File "/home/bijayregmi/.local/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 8876, in ReadImage
    return _SimpleITK.ReadImage(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'ReadImage'.
  Possible C/C++ prototypes are:
    itk::simple::ReadImage(std::vector< std::string,std::allocator< std::string > > const &,itk::simple::PixelIDValueEnum,std::string const &)
    itk::simple::ReadImage(std::string const &,itk::simple::PixelIDValueEnum,std::string const &)

```

**Comment by mrajchl** [comment]
Please read the note in the README file. In accordance with scipy and numpy, we are not supporting python 2.x anymore. I am pretty certain this is due to some issue with string parsing. Could you run this in a python3 environment and confirm this problem?

**Comment by regmibijay** [comment]
Script runs fine on python3. Indeed a problem in python 2.x environment.

**Comment by mrajchl** [comment]
Thanks for confirming!
